# Generated by Django 3.2.7 on 2021-10-31 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20211028_0904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
        migrations.DeleteModel(
            name='students',
        ),
        migrations.DeleteModel(
            name='teacher',
        ),
        migrations.AddField(
            model_name='addcourse',
            name='classes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addcourse',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
