# Generated by Django 3.2.7 on 2021-11-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bmi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.FloatField(),
        ),
    ]
