# Generated by Django 3.2.7 on 2021-11-04 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20211102_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('day', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=50)),
                ('class_link', models.CharField(max_length=500)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.addcourse')),
            ],
        ),
    ]
