# Generated by Django 3.2.7 on 2021-11-04 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_auto_20211104_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='day',
            field=models.CharField(max_length=25),
        ),
    ]
