# Generated by Django 3.2.7 on 2021-11-06 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0010_alter_timetable_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='reschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_day', models.CharField(max_length=15)),
                ('s_time', models.CharField(max_length=50)),
                ('r_day', models.CharField(max_length=15)),
                ('r_time', models.CharField(max_length=50)),
                ('reason', models.CharField(max_length=500)),
                ('today', models.DateField()),
                ('status', models.IntegerField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
