# Generated by Django 3.2.7 on 2021-11-06 10:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0011_reschedule'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reschedule',
            new_name='reschedule_req',
        ),
    ]
