# Generated by Django 3.2.7 on 2021-11-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0012_rename_reschedule_reschedule_req'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reschedule_req',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
