# Generated by Django 3.2.7 on 2021-11-07 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0014_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='myname',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='myname', to='auth.user'),
            preserve_default=False,
        ),
    ]
